spring:
  cloud:
    gateway:
      routes:
        - id: msvc-cursos
          uri: lb://msvc-cursos
          predicates:
            - Path=/cursos/**
          filters:
            - StripPrefix=1
        - id: msvc-usuarios
          uri: lb://msvc-usuarios
          predicates:
            - Path=/usuarios/**
          filters:
            - StripPrefix=1